language: cpp

dist: bionic
os: linux
compiler: clang

addons:
    apt:
        update: true
        packages: &common_packages
            - build-essential
            - cmake
            - libxcursor-dev
            - libxi-dev
            - libxinerama-dev
            - libxrandr-dev
            - python3-distutils
            - libstdc++-7-dev

before_install:

before_script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DSCIN_USE_SWIFTSHADER=ON -DPYTHON_EXECUTABLE=`which python3` ..

script:
    - make run_unittests
    - src/run_unittests

