language: cpp

matrix:
    include:
        - os: linux
          dist: bionic
          compiler: clang
          env:
              - CC=clang-8 CXX=clang++-8
              - DO_COVERAGE=true
        - os: linux
          dist: bionic
          env:
              - DO_COVERAGE=false
        - os: osx
          osx_image: xcode11
          env:
              - DO_COVERAGE=false

cache: ccache

before_install:
    - $TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh

before_script:
    - $TRAVIS_BUILD_DIR/.travis/before-script-$TRAVIS_OS_NAME.sh

script:
    - $TRAVIS_BUILD_DIR/.travis/script-$TRAVIS_OS_NAME.sh

before_deploy:
    - export $TRAVIS_TAG=0.0.4 # remove me after testing!
    - $TRAVIS_BUILD_DIR/.travis/before-deploy-$TRAVIS_OS_NAME.sh

deploy:
    # coverage reports and documentation
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/artifacts
      upload-dir: artifacts/$TRAVIS_COMMIT
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        condition: $DO_COVERAGE = true
        branch: master
    # build artifacts
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/builds
      upload-dir: builds
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        branch: master
    # releases
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/releases
      upload-dir: releases
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      all_branches: true  # remove me after testing!
      on:
        tags: true

