language: cpp

dist: trusty
os:
    - linux

addons:
    apt:
        packages: &common_packages
            - build-essential
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev

before_install:
    - sudo apt-get update -qq

before_script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..

script:
    - make run_unittests

