language: cpp

dist: trusty
os: linux

addons:
    apt:
        update: true
        sources:
            - deadsnakes
        packages: &common_packages
            - build-essential
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - python3-distutils

before_install:

before_script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..

script:
    - make run_unittests

