# encrypted key password for symbol_upload_key_password
env:
  global:
    secure: "oiE4MugKsUd9+KI7++HYMbJHS8yLsFnlmcm0/x2w6Hl2dLoFaiy3TYbJF6qm2kUG82wlFtD97PNLKFNY6/JKqytD82U0MosfnFlQFboZr8gsjeeyTjdXDNaUIKlvzhaDGpwK15kuE5nn6lM4szIdqZQyBSIGpvig1w5Wju1v2vBJmnQ6Vc2dv1ES6Bk6SRQ5kvj5LWWVuvj/rSz2UGOA9zOtrbEv9w8oIKts9X47TNbshETi6+v74ZaVdK91WvtwWzNSDhmbo3F/S4Rs6kqFXjMfOeismdKq90yv+FTmrpS5y9j6b07V4lzM2qePd96LJ+RYKl1wkLsUENxWchyhetDp0IBDnu2D0IxMa4G4in3rMuv764p6U1DuJ+LSfBbHe1ohVnkKyoScsWK+sklBD3xZIDyFYvV0wEoDd7+Unj9f4XO0KMyTaYTqu3PEkCdkInPGnX9OrtVxbpYhjanZBSCDeRM219fXDNMIJ2q1FM8Q+NjeoeChV3FtSZdDgRoLi9xMz/8od+Oexf5tZje6bpT0SOp40HiPJNPdktXtSnUxIPTQHYEOeunuUcFGHGk1oYSARUcaBqTR8TJwTsBr1pjBasEWOS+xV7U5fE3jfOBrIOfFh6yBWpv3/Fz6GEylDLs9rrnDn8yRtaYNTxmPQ33NGm+JOJ+bSBCoGIDM6LU="

language: cpp
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: clang
    env:
    - CC=clang-8 CXX=clang++-8
    - DO_COVERAGE=true
  - os: linux
    dist: bionic
    env:
    - DO_COVERAGE=false
  - os: osx
    osx_image: xcode11
    env:
    - DO_COVERAGE=false
  - os: windows
    env:
    - DO_COVERAGE=false
before_install:
- openssl aes-256-cbc -pbkdf2 -k $symbol_upload_key_password -in .travis_symbol_upload_key.json.enc -out .travis_symbol_upload_key.json -d
- "$TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh"
before_script:
- "$TRAVIS_BUILD_DIR/.travis/before-script-$TRAVIS_OS_NAME.sh"
script:
- "$TRAVIS_BUILD_DIR/.travis/script-$TRAVIS_OS_NAME.sh"
before_deploy:
- "$TRAVIS_BUILD_DIR/.travis/before-deploy-$TRAVIS_OS_NAME.sh"
deploy:
- provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: scintillator-synth-coverage
  local-dir: "$HOME/artifacts"
  upload-dir: artifacts/$TRAVIS_COMMIT
  verbose: true
  edge: true
  cleanup: false
  acl: public_read
  on:
    condition: "$DO_COVERAGE = true"
    branch: master
- provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: scintillator-synth-coverage
  local-dir: "$HOME/builds"
  upload-dir: builds
  verbose: true
  edge: true
  cleanup: false
  acl: public_read
  on:
    condition: "$DO_COVERAGE = false"
    branch: master
- provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: scintillator-synth-coverage
  local-dir: "$HOME/releases"
  upload-dir: releases
  verbose: true
  edge: true
  cleanup: false
  acl: public_read
  on:
    tags: true
    condition: "$DO_COVERAGE = false"
    all_branches: true
- provider: gcs
  key_file: ".travis_symbol_upload_key.json"
  bucket: scintillator-gargamelle-symbols
  cleanup: false
  on:
    condition: "$DO_COVERAGE = false"
    branch: master

