language: cpp

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: bionic
          compiler: clang
          env:
              - CC=clang-8 CXX=clang++-8
        - os: osx
          osx_image: xcode9.4

cache: ccache

before_install:
    - $TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh

before_script:
    - mkdir build && cd build
    - $TRAVIS_BUILD_DIR/.travis/before-script-$TRAVIS_OS_NAME.sh

script:
    - $TRAVIS_BUILD_DIR/.travis/script-$TRAVIS_OS_NAME.sh

before_deploy:
    - mkdir -p $HOME/artifacts/coverage
    - cp $TRAVIS_BUILD_DIR/build/src/scinsynth_coverage.json $HOME/artifacts
    - cp -R $TRAVIS_BUILD_DIR/build/doc $HOME/artifacts
    - cp -R $TRAVIS_BUILD_DIR/build/report $HOME/artifacts

deploy:
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/artifacts
      upload-dir: artifacts/$TRAVIS_COMMIT
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        condition: $TRAVIS_OS_NAME = linux
        branch: master
