language: cpp

sudo: required
dist: trusty
os:
    - linux

before_install:
    - sudo apt-get update
    - sudo apt-get install --yes build-essential cmake libvulkan-dev libxinerama-dev libxcursor-dev libvulkan-dev vulkan-validationlayers libxi-dev libxrandr-dev libgl-dev gperf python3-distutils

before_script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..

script:
    - make

