language: cpp

dist: bionic
os: linux
compiler: clang
cache: ccache

addons:
    apt:
        update: true
        packages: &common_packages
            - build-essential
            - clang-8
            - clang-format-8
            - cmake
            - doxygen
            - gperf
            - imagemagick
            - libavcodec-dev
            - libavformat-dev
            - libc++-8-dev
            - libc++abi-8-dev
            - libwayland-dev
            - libxcursor-dev
            - libxi-dev
            - libxinerama-dev
            - libxrandr-dev
            - llvm-8-dev
            - python3-distutils
            - python3-yaml
            - supercollider-language
            - zlib1g

env:
    - CC=clang-8 CXX=clang++-8 DISPLAY=:99 QT_PLATFORM_PLUGIN=offscreen

before_install:

before_script:
    - mkdir build
    - mkdir third_party/vulkan-dev/build && cd third_party/vulkan-dev/build
    - cmake -DSCIN_USE_OWN_VULKAN=ON ..
    - make -j2 install
    - make -j2 local-vulkan-utils
    - cd ../../../build
    - cmake -DSCIN_BUILD_DOCS=ON -DSCIN_USE_OWN_VULKAN=ON -DCMAKE_BUILD_TYPE=Coverage -DLLVM_COV="llvm-cov-8" -DLLVM_PROFDATA="llvm-profdata-8" -DPYTHON_EXECUTABLE=`which python3` ..

script:
    - make -j2 compare_images
    - make -j2 coverage_report
    - make -j2 lintall
    - make -j2 docs

before_deploy:
    - mkdir -p $HOME/artifacts/coverage
    - cp $TRAVIS_BUILD_DIR/build/src/scinsynth_coverage.json $HOME/artifacts
    - cp -R $TRAVIS_BUILD_DIR/build/doc $HOME/artifacts
    - cp -R $TRAVIS_BUILD_DIR/build/report $HOME/artifacts

deploy:
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/artifacts
      upload-dir: artifacts/$TRAVIS_COMMIT
      verbose: true
      edge: true
      skip_cleanup: true
      on:
        branch: master
