language: cpp

dist: bionic
os: linux
compiler: clang
cache: ccache

addons:
    apt:
        sources:
            - sourceline: 'deb https://packages.lunarg.com/vulkan bionic main'
              key_url: 'http://packages.lunarg.com/lunarg-signing-key-pub.asc'
        update: true
        packages: &common_packages
            - build-essential
            - clang-8
            - clang-format-8
            - cmake
            - doxygen
            - glslang-dev
            - gperf
            - imagemagick
            - libasound2-dev
            - libavcodec-dev
            - libavformat-dev
            - libc++-8-dev
            - libc++abi-8-dev
            - libfftw3-dev
            - libicu-dev
            - libjack-jackd2-dev
            - libreadline6-dev
            - libudev-dev
            - libvulkan-dev
            - libwayland-dev
            - libxcursor-dev
            - libxi-dev
            - libxinerama-dev
            - libxrandr-dev
            - llvm-8-dev
            - pkg-config
            - python3-distutils
            - python3-yaml
            - shaderc
            - spirv-headers
            - spirv-tools
            - vulkan-headers
            - vulkan-validationlayers
            - zlib1g

env:
    - CC=clang-8 CXX=clang++-8

before_install:

before_script:
    - mkdir build
    - mkdir third_party/sclang-dev/build && cd third_party/sclang-dev/build
    - cmake ..
    - make -j2 install
    - cd ../../../build
    - cmake -DSCIN_BUILD_DOCS=ON -DCMAKE_BUILD_TYPE=Coverage -DLLVM_COV="llvm-cov-8" -DLLVM_PROFDATA="llvm-profdata-8" -DPYTHON_EXECUTABLE=`which python3` -DSCIN_SCLANG=$TRAVIS_BUILD_DIR/build/install-ext/bin/sclang ..

script:
    - make -j2 swiftshader-local
    - make -j2 install
    - make -j2 coverage_report
    - make -j2 lintall
    - make -j2 docs

before_deploy:
    - mkdir -p $HOME/artifacts/coverage
    - cp $TRAVIS_BUILD_DIR/build/src/scinsynth_coverage.json $HOME/artifacts
    - cp -R $TRAVIS_BUILD_DIR/build/doc $HOME/artifacts
    - cp -R $TRAVIS_BUILD_DIR/build/report $HOME/artifacts

deploy:
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/artifacts
      upload-dir: artifacts/$TRAVIS_COMMIT
      verbose: true
      edge: true
      skip_cleanup: true
      on:
        branch: master
