language: cpp

matrix:
    include:
        - os: linux
          dist: bionic
          compiler: clang
          env:
              - CC=clang-8 CXX=clang++-8
        - os: osx
          osx_image: xcode11

cache: ccache

before_install:
    - $TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh

before_script:
    - $TRAVIS_BUILD_DIR/.travis/before-script-$TRAVIS_OS_NAME.sh

script:
    - $TRAVIS_BUILD_DIR/.travis/script-$TRAVIS_OS_NAME.sh

before_deploy:
    - $TRAVIS_BUILD_DIR/.travis/before-deploy-$TRAVIS_OS_NAME.sh

deploy:
    # coverage reports and documentation
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/artifacts
      upload-dir: artifacts/$TRAVIS_COMMIT
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        condition: $TRAVIS_OS_NAME = linux
        branch: master
    # build artifacts
    - provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: scintillator-synth-coverage
      local-dir: $HOME/builds
      upload-dir: builds
      verbose: true
      edge: true
      cleanup: false
      acl: public_read
      on:
        branch: master
