#!/bin/bash

# custom AppRun because the default one swallows stdio for windowing applications, but we need the logstreams, and to
# also just forward the arguments.
HERE="$(dirname "$(readlink -f "${0}")")"
exec "$HERE/usr/bin/scinsynth" "$@"

